---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

file="C:/Users/Nicholas/Downloads/repdata%2Fdata%2Factivity/activity.csv"
activity<-read.csv(file, header = TRUE, colClass=c('integer', 'Date', 'integer'))

## What is mean total number of steps taken per day?

daytotal<-aggregate(steps ~ date, activity, sum)
barplot(daytotal$steps,xlab="date",ylab="steps for day",main="Daily steps by date")
mean(daytotal$steps)
median(daytotal$steps)

## What is the average daily activity pattern?
interval.total<-aggregate(steps ~ interval, activity, mean)
plot(interval.total,type='1')

## The 5-minute interval that, on average, contains the maximum number of steps 
max<-which.max(interval.total$steps)
interval.total$interval[max]

## Imputing missing values
sum(is.na(activity$steps))

Fill in a missing NA with the average number of steps in the same 5-min interval.
Create a new dataset as the original and use tapply for filling in the missing values with the average number of steps per 5-minute interval:
activity2 <- activity
nas <- is.na(data_full$steps)
avg_interval <- tapply(data_full$steps, data_full$interval, mean, na.rm=TRUE, simplify=TRUE)
data_full$steps[nas] <- avg_interval[as.character(data_full$interval[nas])]
Check that there are no missing values:

activity.clean <- merge(activity, steps.date, by="date", suffixes=c("", ".mean"))
nas <- is.na(activity.clean$steps)
activity.clean$steps[nas] <- activity.clean$steps.mean[nas]
activity.clean <- activity.clean[, c(1:3)]
head(activity.clean)


sum(is.na(data_full$steps))
## [1] 0
No more missing values.





## Histogram of the total number of steps taken each day after missing values are imputed

## Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends

## All of the R code needed to reproduce the results (numbers, plots, etc.) in the report

## Are there differences in activity patterns between weekdays and weekends?
